# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0002_auto_20170330_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='numero_cuenta',
            new_name='numero_telefono',
        ),
    ]
