# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0003_auto_20170330_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(upload_to='portada'),
        ),
    ]
